/* ================================================================
   TRANSACTION MODEL
   Stores every payment attempt (one-time and subscription initial)
   
   Fields are designed to mirror Paystack's transaction object
   so verification data can be stored accurately.
================================================================ */

'use strict';

const mongoose = require('mongoose');

/* ================================================================
   TRANSACTION SCHEMA
================================================================ */
const TransactionSchema = new mongoose.Schema(
  {
    /* ------------------------------------------------------------
       CORE IDENTIFIERS
    ------------------------------------------------------------ */

    // Unique payment reference — generated by frontend (ACI-timestamp-random)
    reference: {
      type:      String,
      required:  [true, 'Transaction reference is required'],
      unique:    true,
      trim:      true,
      index:     true,
      maxlength: [100, 'Reference cannot exceed 100 characters'],
    },

    // Paystack's internal transaction ID (set after verification)
    paystack_id: {
      type:    Number,
      default: null,
    },

    // Paystack access code (from initialize response)
    access_code: {
      type:    String,
      default: null,
      trim:    true,
    },

    /* ------------------------------------------------------------
       DONOR INFORMATION
    ------------------------------------------------------------ */

    // Donor email address (required for Paystack)
    email: {
      type:      String,
      required:  [true, 'Donor email is required'],
      lowercase: true,
      trim:      true,
      index:     true,
      match: [
        /^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$/,
        'Please provide a valid email address',
      ],
    },

    // Donor name (optional — from metadata)
    donor_name: {
      type:      String,
      default:   'Anonymous',
      trim:      true,
      maxlength: [100, 'Name cannot exceed 100 characters'],
    },

    // Donor dedication/message
    donor_message: {
      type:      String,
      default:   '',
      trim:      true,
      maxlength: [300, 'Message cannot exceed 300 characters'],
    },

    // Paystack customer code (set after verification)
    customer_code: {
      type:    String,
      default: null,
      trim:    true,
    },

    /* ------------------------------------------------------------
       PAYMENT DETAILS
    ------------------------------------------------------------ */

    // Amount in KOBO (100 kobo = ₦1)
    // Always stored in kobo to match Paystack's format
    amount: {
      type:     Number,
      required: [true, 'Transaction amount is required'],
      min:      [50000, 'Minimum amount is 50000 kobo (₦500)'],
    },

    // Currency code
    currency: {
      type:    String,
      default: 'NGN',
      enum:    ['NGN', 'GHS', 'ZAR', 'USD', 'KES'],
      trim:    true,
    },

    // Payment channel used (card, bank, ussd, bank_transfer, etc.)
    channel: {
      type:    String,
      default: null,
      trim:    true,
      enum:    [
        'card',
        'bank',
        'ussd',
        'qr',
        'mobile_money',
        'bank_transfer',
        'eft',
        null,
      ],
    },

    // Payment gateway response message
    gateway_response: {
      type:    String,
      default: null,
      trim:    true,
    },

    /* ------------------------------------------------------------
       TRANSACTION TYPE
    ------------------------------------------------------------ */

    // Payment mode
    mode: {
      type:    String,
      required: [true, 'Transaction mode is required'],
      enum:    ['one-time', 'subscription'],
      default: 'one-time',
      index:   true,
    },

    // Associated plan code (for subscription payments)
    plan_code: {
      type:    String,
      default: null,
      trim:    true,
    },

    // Subscription code (set after subscription is created via webhook)
    subscription_code: {
      type:    String,
      default: null,
      trim:    true,
      index:   true,
    },

    /* ------------------------------------------------------------
       TRANSACTION STATUS
    ------------------------------------------------------------ */

    // Payment status
    status: {
      type:    String,
      required: true,
      enum:    ['pending', 'success', 'failed', 'abandoned', 'reversed'],
      default: 'pending',
      index:   true,
    },

    // Whether this transaction has been verified on the backend
    // (prevents fake success from frontend manipulation)
    verified: {
      type:    Boolean,
      default: false,
    },

    // Timestamp of when verification was done
    verified_at: {
      type:    Date,
      default: null,
    },

    // Number of verification attempts (for polling audit)
    verification_attempts: {
      type:    Number,
      default: 0,
      min:     0,
    },

    /* ------------------------------------------------------------
       CARD AUTHORIZATION (for future recurring charges)
       Only stored for reusable authorizations
    ------------------------------------------------------------ */
    authorization: {
      authorization_code: { type: String, default: null },
      card_type:          { type: String, default: null },
      last4:              { type: String, default: null },
      exp_month:          { type: String, default: null },
      exp_year:           { type: String, default: null },
      bin:                { type: String, default: null },
      bank:               { type: String, default: null },
      channel:            { type: String, default: null },
      signature:          { type: String, default: null },
      reusable:           { type: Boolean, default: false },
      country_code:       { type: String, default: null },
    },

    /* ------------------------------------------------------------
       METADATA & AUDIT
    ------------------------------------------------------------ */

    // Raw Paystack response (stored for debugging/reconciliation)
    paystack_raw_response: {
      type:   mongoose.Schema.Types.Mixed,
      default: null,
      select: false, // Don't return by default (security)
    },

    // Client IP address at time of payment
    ip_address: {
      type:    String,
      default: null,
      trim:    true,
    },

    // User agent string
    user_agent: {
      type:    String,
      default: null,
      trim:    true,
      maxlength: 500,
    },

    // Whether webhook has confirmed this transaction
    webhook_confirmed: {
      type:    Boolean,
      default: false,
    },

    // Timestamp when webhook arrived
    webhook_received_at: {
      type:    Date,
      default: null,
    },

    // Paid at timestamp from Paystack
    paid_at: {
      type:    Date,
      default: null,
    },
  },
  {
    /* ------------------------------------------------------------
       SCHEMA OPTIONS
    ------------------------------------------------------------ */
    timestamps: true,          // Adds createdAt and updatedAt
    collection: 'transactions', // Explicit collection name
    toJSON: {
      virtuals: true,
      transform: function(doc, ret) {
        // Remove sensitive fields from JSON output
        delete ret.paystack_raw_response;
        delete ret.__v;
        return ret;
      },
    },
    toObject: { virtuals: true },
  }
);

/* ================================================================
   VIRTUAL FIELDS
================================================================ */

// Amount in NGN (kobo / 100)
TransactionSchema.virtual('amount_ngn').get(function () {
  return this.amount / 100;
});

// Human-readable status
TransactionSchema.virtual('status_display').get(function () {
  const map = {
    pending:   '⏳ Pending',
    success:   '✅ Successful',
    failed:    '❌ Failed',
    abandoned: '🚫 Abandoned',
    reversed:  '↩️ Reversed',
  };
  return map[this.status] || this.status;
});

// Is this a recurring donation?
TransactionSchema.virtual('is_recurring').get(function () {
  return this.mode === 'subscription';
});

/* ================================================================
   INDEXES
================================================================ */
// Compound index for donor lookup
TransactionSchema.index({ email: 1, createdAt: -1 });

// Index for status filtering
TransactionSchema.index({ status: 1, createdAt: -1 });

// Index for webhook processing (idempotency)
TransactionSchema.index({ reference: 1, webhook_confirmed: 1 });

/* ================================================================
   STATIC METHODS
================================================================ */

/**
 * Find transaction by reference
 * @param {string} reference
 * @returns {Promise<Transaction>}
 */
TransactionSchema.statics.findByReference = function (reference) {
  return this.findOne({ reference: reference.trim() });
};

/**
 * Get all donations by email
 * @param {string} email
 * @returns {Promise<Transaction[]>}
 */
TransactionSchema.statics.findByEmail = function (email) {
  return this.find({ email: email.toLowerCase().trim() })
    .sort({ createdAt: -1 })
    .select('-paystack_raw_response');
};

/**
 * Get total amount donated (successful transactions only)
 * @returns {Promise<number>} Total in kobo
 */
TransactionSchema.statics.getTotalDonated = async function () {
  const result = await this.aggregate([
    { $match: { status: 'success' } },
    { $group: { _id: null, total: { $sum: '$amount' } } },
  ]);
  return result.length > 0 ? result[0].total : 0;
};

/**
 * Get donation count by mode
 * @returns {Promise<object>}
 */
TransactionSchema.statics.getCountByMode = async function () {
  const result = await this.aggregate([
    { $match: { status: 'success' } },
    { $group: { _id: '$mode', count: { $sum: 1 } } },
  ]);
  return result.reduce((acc, item) => {
    acc[item._id] = item.count;
    return acc;
  }, {});
};

/* ================================================================
   INSTANCE METHODS
================================================================ */

/**
 * Mark transaction as successfully verified
 * @param {object} paystackData - Paystack verification response
 */
TransactionSchema.methods.markSuccess = async function (paystackData) {
  this.status            = 'success';
  this.verified          = true;
  this.verified_at       = new Date();
  this.paystack_id       = paystackData.id;
  this.channel           = paystackData.channel;
  this.gateway_response  = paystackData.gateway_response;
  this.customer_code     = paystackData.customer?.customer_code;
  this.paid_at           = paystackData.paid_at
    ? new Date(paystackData.paid_at)
    : new Date();

  // Save authorization if reusable
  if (paystackData.authorization?.reusable) {
    this.authorization = {
      authorization_code: paystackData.authorization.authorization_code,
      card_type:          paystackData.authorization.card_type,
      last4:              paystackData.authorization.last4,
      exp_month:          paystackData.authorization.exp_month,
      exp_year:           paystackData.authorization.exp_year,
      bin:                paystackData.authorization.bin,
      bank:               paystackData.authorization.bank,
      channel:            paystackData.authorization.channel,
      signature:          paystackData.authorization.signature,
      reusable:           true,
      country_code:       paystackData.authorization.country_code,
    };
  }

  return this.save();
};

/**
 * Mark transaction as failed
 * @param {string} reason
 */
TransactionSchema.methods.markFailed = async function (reason) {
  this.status           = 'failed';
  this.gateway_response = reason || 'Transaction failed';
  return this.save();
};

/* ================================================================
   PRE-SAVE HOOKS
================================================================ */
TransactionSchema.pre('save', function (next) {
  // Normalize email
  if (this.email) {
    this.email = this.email.toLowerCase().trim();
  }

  // Increment verification attempts counter
  if (this.isModified('verified')) {
    this.verification_attempts += 1;
  }

  next();
});

/* ================================================================
   MODEL EXPORT
================================================================ */
const Transaction = mongoose.model('Transaction', TransactionSchema);
module.exports = Transaction;
